spring:
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: none
    hibernate.show-sql: true
  datasource:
    url: jdbc:postgresql://172.17.0.1:5432/pwc?currentSchema=cms
    username: postgres
    password: root


server:
  port: 8899

jwt:
  secret: mhjwtkeyja
  jwtExpiration: 18000